# fly.toml app configuration file generated for sveltefly on 2023-06-05T10:09:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sveltefly"
primary_region = "cdg"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
